### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by smaragdus** [Bluegrams/Vividl#1]
First I would like to say that for me [Vividl](https://sourceforge.net/projects/vividl/) is the best GUI for [youtube-dl](https://ytdl-org.github.io/youtube-dl/) I have ever tested. This project is very promising and I hope that it would not be short-lived (there are many youtube-dl front-ends which were abandoned).

I tested [version](https://sourceforge.net/projects/vividl/files/) [0.1.0](https://sourceforge.net/projects/vividl/files/v.0.1.0/) (portable) and it crashed when:

- context menu command `Copy Video URL` was executed;
- context menu command `Reload Video` was executed;

**Screen:**

![Vividl 0 1 0 0 - 2020-01-25 - crash - 001](https://user-images.githubusercontent.com/9025757/73115846-f0dbb000-3f34-11ea-9d90-c883508cf00c.png)

I use [Vividl](https://github.com/Bluegrams/Vividl) on Windows 8 x64 and have  .NET Framework version 4.6.2 installed.

Are you able to reproduce and confirm these crashes?

**Comment by alxnull** [comment]
Thank you for reporting this. I can confirm the crashes for both commands for videos that could not be fetched successfully. They should however work for videos that were fetched correctly.

Fixes for both bugs will be released with the next version.

**Comment by smaragdus** [comment]
@alxnull 

Thanks for the quick response and fix.

**Comment by smaragdus** [comment]
@alxnull 

> Thank you for reporting this. I can confirm the crashes for both commands for videos that could not be fetched successfully. They should however work for videos that were fetched correctly.

If video was successfully downloaded command `Reload Video` works fine but command `Copy Video URL` still crashes the program. Perhaps my system is to blame for the crash?

**Comment by alxnull** [comment]
The new [v.0.1.1](https://github.com/Bluegrams/Vividl/releases/tag/v.0.1.1) including the fixes for the app crashes and the portable mode [is now available](https://sourceforge.net/projects/vividl/files/v.0.1.1/). Please report back if this has solved your issues. Thanks.

**Comment by smaragdus** [comment]
@alxnull 

I got version [0.1.1](https://sourceforge.net/projects/vividl/files/v.0.1.1/) and everything works fine with the exception of 'Copy Video URL' command, which, when executed, still crashes the program on my end. I suppose that if you cannot reproduce the problem it would not be easy to fix it. Perhaps the problem is with my system, I do not know.
