### ISSUE TITLE
How do I specify the video quality?

### ISSUE THREAD

**Issue by Cy9oz** [Bluegrams/Vividl#106]
How do I specify that the video to be downloaded is always 480P in the "Specify download arguments" section in the settings?
Can someone please give me the command...

**Comment by alxnull** [comment]
The upcoming release will add a new option to specify a preferred video resolution to download. This will result in Vividl automatically preferring formats with the specified resolution for direct downloads and video conversion downloads. The new options is available via:
- the settings window at "General -> Download List -> Preferred Video Resolution"
- the window for adding new videos when expanding the "Options" section
