### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by nero1st** [Bluegrams/Vividl#11]
In some cases it is necessary to provide username and password credentials in order to be able to fetch stream.
It would be great if Vividl could support that.

Regards

**Comment by alxnull** [comment]
Definitely a feature that we should add. Would you have an example of such a case?

**Comment by nero1st** [comment]
For sure. Here it is: https://www.crunchyroll.com/pt-br/tower-of-god/episode-11-underwater-hunt-part-one-794529
Any new episode just released will do.

In this case, you must also have a premium subscription on the account. Otherwise, youtube-dl will return that is just a sample.
I think that the inclusion of an option that allows you to freely use (or not) your credentials for specific websites is the best way forward; not just when asked.

Regards

**Comment by nero1st** [comment]
For sure. Here it is: https://www.crunchyroll.com/pt-br/tower-of-god/episode-11-underwater-hunt-part-one-794529 (Any new episode just released will do).

In this case, you must also have a premium subscription on the account. Otherwise, youtube-dl will return that is just a sample.

I think that the inclusion of an option that allows you to freely use (or not) your credentials for specific websites is the best way forward; not just when asked.

Regards

**Comment by alxnull** [comment]
@nero1st I added basic support for authentication in the window for adding new urls (`File -> Add New Videos`) at https://github.com/Bluegrams/Vividl/tree/develop. Please have a look if the implementation works and fits your needs.

You can download a pre-built preview from this branch at https://vividl.sourceforge.io/vividl-pre-releases/Vividl-v.0.3.0-develop-Portable.zip or built the `develop` branch of this repo yourself.

Thanks!

**Comment by alxnull** [comment]
Released with [v.0.3.0](https://github.com/Bluegrams/Vividl/releases/tag/v.0.3.0).
