### ISSUE TITLE
Fail to fetch video

### ISSUE THREAD

**Issue by smaragdus** [Bluegrams/Vividl#2]
[Vividl](https://sourceforge.net/projects/vividl/) fails to fetch a certain YouTube video ([YouTube link](https://www.youtube.com/watch?v=q13W_HcLkNM)),

**Screen:**

![Vividl 0 1 0 0 - 2020-01-25 - error - 001](https://user-images.githubusercontent.com/9025757/73115930-b83cd600-3f36-11ea-9089-ebd4f82f2e1f.png)

When I try to use context menu command `Reload Video` [Vividl](https://github.com/Bluegrams/Vividl) crashes (the crash was already reported- issue #1)

I have to say that I tried to get this particular video with another [youtube-dl](https://ytdl-org.github.io/youtube-dl/) front-end- [YDL-UI](https://github.com/Maxstupo/ydl-ui):

**Screen:**

![YDL-UI 2 6 4 - 2020-01-25 - 001](https://user-images.githubusercontent.com/9025757/73115996-dc4ce700-3f37-11ea-9fdd-2dbbc3dafb1f.png)

but it does not crash when I try to restart it.

I suppose that the problem is within [youtube-dl](https://ytdl-org.github.io/youtube-dl/) yet since I encountered it I am reporting it.

**Comment by alxnull** [comment]
This seems to be a known bug of youtube-dl (see [youtube-dl#23819](https://github.com/ytdl-org/youtube-dl/issues/23819)) which has been fixed in the newest release **[2020.01.24](https://github.com/ytdl-org/youtube-dl/releases/tag/2020.01.24)**.

As the current version of Vividl ships with an older version of youtube-dl, please try to update it manually by clicking _"Check for Updates"_ in the settings under `Options -> Settings -> Binaries`.

**Comment by smaragdus** [comment]
@alxnull 

Thank you for the tip and for the information you provided.

[Vividl](https://sourceforge.net/projects/vividl/) [version](https://sourceforge.net/projects/vividl/files/) [0.1.0](https://sourceforge.net/projects/vividl/files/v.0.1.0/) comes packaged with [youtube-dl](https://ytdl-org.github.io/youtube-dl/) [version](https://github.com/ytdl-org/youtube-dl/releases) [2020.01.15](https://github.com/ytdl-org/youtube-dl/releases/tag/2020.01.15)- I tried again to get the same video and this time it was downloaded successfully, strange. Anyway, I updated [youtube-dl](https://ytdl-org.github.io/youtube-dl/) to [version](https://github.com/ytdl-org/youtube-dl/releases) [2020.01.24](https://github.com/ytdl-org/youtube-dl/releases/tag/2020.01.24) and it also downloads without problems.

**Comment by smaragdus** [comment]
@alxnull 

As this is an external problem related to [youtube-dl](https://ytdl-org.github.io/youtube-dl/) and as it seems to be fixed with the latest version ([2020.01.24](https://github.com/ytdl-org/youtube-dl/releases/tag/2020.01.24)) I think this issue can be closed. I am not closing it myself because you may have some considerations to keep it open.
