### ISSUE TITLE
"ERROR: unable to overwrite current version" when updating youtube-dl

### ISSUE THREAD

**Issue by Mennaruuk** [Bluegrams/Vividl#26]
Thank you for making this great app, I use it often and it's awesome. I've been running into a small issue. [youtube-dl ](https://youtube-dl.org/)is not updating for an unfathomable reason. As of now, videos are still downloading though. But I keep running into the error below whenever I attempt to update [youtube-dl](https://youtube-dl.org/). It's still using the November 1 release as opposed to the latest November 26. I wish there was an auto-update feature for youtube-dl, or maybe there is but it isn't functioning for me.

![image](https://user-images.githubusercontent.com/52135169/100406620-4c366d00-3034-11eb-8932-71d28b6d1b66.png)

**Comment by alxnull** [comment]
Hi,

glad to hear this app is useful to you. Your error message seems to indicate that youtube-dl isn't allowed to write to the folder where it is saved. If you have installed Vividl using the installer, youtube-dl is installed in the Program Files folder, so you might need to start Vividl with admin priviledges to update. (This is not ideal, so I'll probably try to change it in a future version.)

Also, there's no auto-update feature for youtube-dl currently, Vividl is using the built-in update command of youtube-dl. But this is also a feature worth considering.

**Comment by Mennaruuk** [comment]
It worked! I ran it as admin and I was able to update youtube-dl. Another workaround is manually downloading the latest youtube-dl.exe ([right here](https://youtube-dl.org/downloads/latest/youtube-dl.exe)) then replacing the old youtube-dl.exe, which is by default found at `C:\Program Files (x86)\Bluegrams\Vividl\Lib\youtube-dl.exe`.

And making an auto-update feature for youtube-dl would be a heavenly blessing! Since Vividl already supports checking for updates at startup, so something like that or even auto-updating would be amazing additions to this wonderful software. Thank you for maintaining Vividl, it makes my life easier!

**Comment by alxnull** [comment]
There are two changes in v.0.5.0 related to this:

- youtube-dl.exe is now in the AppData folder by default, so no admin priviledges are required for updating it
- There's a simple automatic update checking for youtube-dl: go to `Settings -> Application -> youtube-dl` and check "Automatically check for updates at startup"

**Comment by Mennaruuk** [comment]
Appreciate it so much dude! Updating both youtube-dl and Vividl have just gotten easier.
