### ISSUE TITLE
Vividl from Chocolatey installation can't save settings

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [Bluegrams/Vividl#29]
It keeps trying to write `portable.config` file into `C:\ProgramData\chocolatey\lib\vividl\tools\vividl` directory when it is not writable by non-administrator users.

**Comment by alxnull** [comment]
Thanks for bringing this up, I'll fix it in a coming release as soon as possible.

**Comment by alxnull** [comment]
I've uploaded a patched package to chocolatey recently. Please check if that fixes this issue.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
It seems everything good since version 20210228, thanks!
