### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by smaragdus** [Bluegrams/Vividl#3]
I am glad that there is a portable version of [Vividl](https://sourceforge.net/projects/vividl/) (I always prefer portable programs) but in my opinion [version](https://sourceforge.net/projects/vividl/files/) [0.1.0](https://sourceforge.net/projects/vividl/files/v.0.1.0/) is not fully portable as it still writes to AppData (**user.config** file):

`C:\Users\User\AppData\Local\Bluegrams\Vividl.exe_Url_2emrq3scocpo2mxqxzwbdn50ixbadvyb\0.1.0.0\user.config`

I think that for the portable version of [Vividl](https://github.com/Bluegrams/Vividl) this **user.config** file should be saved next to **portable.config** file in program folder (the folder which contains the executable- **Vividl.exe**) which would make the program fully portable (not writing outside program folder).

**Comment by alxnull** [comment]
I've always tried to release portable versions of my apps since you made me aware of this a while ago :)

What you describe is indeed a bug in the current implementation as Vividl _should_ write all configuration to the `portable.config` file in the executable folder. I've already fixed this and the fix will be released with the next version. Thanks for reporting.

**Comment by smaragdus** [comment]
> I've always tried to release portable versions of my apps since you made me aware of this a while ago :)

I really appreciate that. When I discovered [Vividl](https://github.com/Bluegrams/Vividl) by chance at [AlternativeTo](https://alternativeto.net/software/vividl/) I was glad it was offered as portable version from the very first release. You have a strong memory. By the way I updated [Colora](https://sourceforge.net/projects/colora/) to [version](https://sourceforge.net/projects/colora/files/) [0.3.0](https://sourceforge.net/projects/colora/files/v.0.3.0/) and it is a huge improvement, thanks!

> What you describe is indeed a bug in the current implementation as Vividl should write all configuration to the `portable.config` file in the executable folder. I've already fixed this and the fix will be released with the next version.

Excellent, thanks, I am waiting for the new release.

**Comment by smaragdus** [comment]
@alxnull 

The portable version is really fixed- I downloaded and tested version [0.1.1](https://sourceforge.net/projects/vividl/files/v.0.1.1/) and [Vividl](https://github.com/Bluegrams/Vividl) no longer writes outside its own folder, excellent, thanks.
