### ISSUE TITLE
Failed to fetch video: ol9B7qWXV9Q

### ISSUE THREAD

**Issue by SPG101** [Bluegrams/Vividl#30]
this error happens whenever i try to download a video. is there something wrong with youtube-dl? here is the video im trying to download: https://www.youtube.com/watch?v=oI9B7qWXV9Q

**Comment by SPG101** [comment]
screenshot of the error in action
![image](https://user-images.githubusercontent.com/81791548/113379612-ce120c00-932e-11eb-86af-e96464d808c1.png)

**Comment by SPG101** [comment]
update: i updated the youtube-dl.exe in the LIB folder to the latest version of youtube-dl (4.1.2021) and now it crashes whenever i try to download a video. did i fuck up?

**Comment by alxnull** [comment]
Hi @SPG101,

upgrading youtube-dl is the right first thing to do when downloading videos fails. However, after upgrading to youtube-dl `2021.4.1.0`, everything works fine for me. If the app crashes, you should get a log in the file `%TEMP%/vividl.log`. Please check that and post it here so we can have a look.

**Comment by alxnull** [comment]
Closing for now, please reopen if the issue persists.
