### ISSUE TITLE
SOCKS5 PROXY

### ISSUE THREAD

**Issue by oneflowa** [Bluegrams/Vividl#32]
Could you please add SOCKS5 proxy option to it ? thanks

**Comment by alxnull** [comment]
Hi, this should already be possible with the right syntax for the proxy url as shown [here](https://github.com/ytdl-org/youtube-dl/issues/14637#issuecomment-340708930).

Go to Options -> Settings -> Download and fill in a proxy url with this format `socks5://username:password@hostname:port/`. Vividl passes this string directly to youtube-dl, so this should work. I haven't tested it yet though.
