### ISSUE TITLE
Add GPU acceleration for FFmpeg

### ISSUE THREAD

**Issue by JosephM101** [Bluegrams/Vividl#34]
It can take a really long time to convert large/long videos. I know that conversion uses FFmpeg, and I believe it's possible to enable GPU acceleration (at least with a port). If that was an option that could be enabled/disabled, that would be awesome, and would significantly increase conversion times.

**Comment by JosephM101** [comment]
It can take a really long time to convert large/long videos. I know that conversion uses FFmpeg, and I believe it's possible to enable GPU acceleration (at least with a port). If that was an option that could be enabled/disabled, that would be awesome, and would significantly increase conversion times.

**Comment by alxnull** [comment]
FFmpeg does seem to support GPU acceleration for MP4 conversions on Nvidia GPUs. I added a settings option to enable this feature in the newest version 0.6.0. It can be enabled via "Settings -> Download -> Use GPU acceleration for video recoding" and should improve conversion times to _MP4 and with CUDA-supported GPUs_.

Hope this helps!
