### ISSUE TITLE
Automatically download highest quality?

### ISSUE THREAD

**Issue by abbeyroad7** [Bluegrams/Vividl#35]
Best direct download is downloading 8k videos at 720p and I'd hate to have to reselect the highest quality option from the dropdown for every video I download. I have the "Download best quality and convert" option ticked as well. Is there something else I'm missing?

**Comment by alxnull** [comment]
Hey @abbeyroad7, could you give an example video link to illustrate what you mean? Thanks!

**Comment by Alann-Mints** [comment]
> Best direct download is downloading 8k videos at 720p and I'd hate to have to reselect the highest quality option from the dropdown for every video I download. I have the "Download best quality and convert" option ticked as well. Is there something else I'm missing?

You can use the merge into mkv option for automatic highest quality

**Comment by alxnull** [comment]
The upcoming release will add a new option to specify a preferred video resolution to download. This will result in Vividl automatically preferring formats with the specified resolution for direct downloads and video conversion downloads. The new options is available via:
- the settings window at "General -> Download List -> Preferred Video Resolution"
- the window for adding new videos when expanding the "Options" section
