### ISSUE TITLE
Migration to yt-dlp

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [Bluegrams/Vividl#37]
Due to a hiatus in development of original project (ytdl-org/youtube-dl#29965) it makes sense to use a more [modern and enhanced fork](https://github.com/yt-dlp/yt-dlp).

**Comment by Mennaruuk** [comment]
Meanwhile, you can specify yt-dlp in the settings. Under **Application**, change the path for youtube-dl to that of yt-dlp:
![Annotation 2021-11-15 004805_censored](https://user-images.githubusercontent.com/52135169/141729140-958f2d9d-f345-4b1a-9e32-671885f7ff1e.jpg)

**Comment by alxnull** [comment]
Agree that this makes sense going forward. Will look into it as soon as possible.

**Comment by alxnull** [comment]
Beginning with the just released version 0.6.0, Vividl now comes with yt-dlp as the download engine by default (included in installer and portable versions and with automatic update checking). For compatibility, it's however also still possible to switch back to youtube-dl manually.
