### ISSUE TITLE
compilazione progetto

### ISSUE THREAD

**Issue by aandroide** [Bluegrams/Vividl#39]
ciao,
come si compila questo progetto per ottenere il file msi?

**Comment by alxnull** [comment]
Translation ([source](https://www.deepl.com/translator#it/en/ciao%2C%0Acome%20si%20compila%20questo%20progetto%20per%20ottenere%20il%20file%20msi%3F)):
> hello,
how to compile this project to get the msi file?

Sorry for the late answer: I'm building the project using [Visual Studio](https://visualstudio.microsoft.com) (currently VS 2019) which needs the C#/.NET desktop development workload installed. To obtain the MSI file, one needs to build the "VividlSetup" project which requires the ["Microsoft Visual Studio Installer Projects" extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects) to be installed.
