### ISSUE TITLE
Keep history

### ISSUE THREAD

**Issue by smaragdus** [Bluegrams/Vividl#4]
I would like to suggest an option for saving download history- perhaps new check box in settings:

- Keep history

which, when enabled, would save download history to file.

For me an option to keep log of downloaded files would be useful.

**Comment by alxnull** [comment]
This has been added in [**v.0.2.0**](https://sourceforge.net/p/vividl/news/2020/03/version-020-of-vividl-released/) (using the download archive feature included in youtube-dl).

**Comment by smaragdus** [comment]
@alxnull 

I could not test 'Use Download Archive' feature because for me version [0.2.0.0](https://sourceforge.net/projects/vividl/files/v.0.2.0/) simply does not work. It can fetch the video, screen:

![Vividl 0 2 0 0 - 2020-03-23 - error - 001](https://user-images.githubusercontent.com/9025757/77281255-3e735f80-6ccf-11ea-8be9-1487c7201d22.png)

but the download never initiates, screen:

![Vividl 0 2 0 0 - 2020-03-23 - error - 002](https://user-images.githubusercontent.com/9025757/77281283-4e8b3f00-6ccf-11ea-8c25-9d5c9d55c568.png)

I tried different videos with different [youtube-dl](https://github.com/ytdl-org/youtube-dl) versions, the downloads never started.

However version [0.1.1.0](https://sourceforge.net/projects/vividl/files/v.0.1.1/) works just fine, it fetches videos, screen:

![Vividl 0 1 1 0 - 2020-03-23 - 006](https://user-images.githubusercontent.com/9025757/77281482-cce7e100-6ccf-11ea-9828-87c3cb5c67b0.png)

and downloads them just right, screen:

![Vividl 0 1 1 0 - 2020-03-23 - 007](https://user-images.githubusercontent.com/9025757/77281520-ea1caf80-6ccf-11ea-9412-cf8a5389e4ad.png)

Are you sure that version [0.2.0.0](https://sourceforge.net/projects/vividl/files/v.0.2.0/) is not faulty?

**Comment by alxnull** [comment]
Sorry to hear that. Unfortunately, I'm currently not able to reproduce this behaviour using either the portable or the installer version, on Windows 10 and on Windows 7. Does this happen only if you check the "Use Download Archive" option or always? Does this happen only for some videos or for all?

P.S.: I disabled update checking temporarily for everyone.

**Comment by smaragdus** [comment]
@alxnull 

I did a new test with new settings and I think that I can shed some light about the problem.

If I use:

**Default download format: Convert to MP4**, screen:

![Vividl 0 2 0 0 - 2020-03-25 - 001](https://user-images.githubusercontent.com/9025757/77490083-941c4900-6e42-11ea-9f74-8e1d0be1aad7.png)

the download starts and finishes successfully, screen:

![Vividl 0 2 0 0 - 2020-03-25 - 002](https://user-images.githubusercontent.com/9025757/77490130-b2824480-6e42-11ea-910d-4060f89ab328.png)

But If I choose:

**Default download format: Best Download**, screens:

![Vividl 0 2 0 0 - 2020-03-25 - 003](https://user-images.githubusercontent.com/9025757/77490189-e65d6a00-6e42-11ea-90df-1133fefdc1b6.png)

![Vividl 0 2 0 0 - 2020-03-25 - 005](https://user-images.githubusercontent.com/9025757/77490329-481dd400-6e43-11ea-8892-412c453d449e.png)

or if I select another format from the drop-down menu, screens:

![Vividl 0 2 0 0 - 2020-03-25 - 004](https://user-images.githubusercontent.com/9025757/77490239-0a20b000-6e43-11ea-92f1-2ac97101eaa8.png)

![Vividl 0 2 0 0 - 2020-03-25 - 006](https://user-images.githubusercontent.com/9025757/77490423-7c919000-6e43-11ea-8f87-d0e866a454b3.png)

download fails. But if I revert to **Convert to MP4**, the download starts and finishes just right, screen:

![Vividl 0 2 0 0 - 2020-03-25 - 008](https://user-images.githubusercontent.com/9025757/77490526-bf536800-6e43-11ea-899e-2bbbec42a060.png)

In short- in my tests when **Convert to MP4** is enabled, all downloads always complete fine, but when I switch to **Best Download** or any other format, all downloads always fail. It seems that manually choosing a format causes the downloads to fail. Can you confirm that?

About **Use Download Archive** feature, screen:

![Vividl 0 2 0 0 - 2020-03-25 - 010](https://user-images.githubusercontent.com/9025757/77491331-240fc200-6e46-11ea-9c3e-04c3ab1009b4.png)

file **.archive.txt** was saved not in program folder (I am using the portable version of [Vividl](https://sourceforge.net/projects/vividl/)) but on Desktop (my default download folder). Moving file **.archive.txt** has no effect, it is always saved on Desktop. I think that **.archive.txt** should be saved in program folder (next to executable- **Vividl.exe**) for portable version and in AppData for installer version. What do you think?

**Comment by alxnull** [comment]
> In short- in my tests when Convert to MP4 is enabled, all downloads always complete fine, but when I switch to Best Download or any other format, all downloads always fail. It seems that manually choosing a format causes the downloads to fail. Can you confirm that?

I was able to reproduce this issue now. If I'm right, the failure happens for the "Best Download" option and all formats that are shown additionally when "Show all available formats" is enabled in the settings. Does this match with your observations?

I've already found the cause for this bug and I'm in the process of fixing it. Thanks again for your patience and your efforts in finding and reporting this issue, really appreciate that. Would you mind testing the application to confirm that the issue is resolved also on your side before I release a new update? (I would provide you a pre-release binary for testing.)

> file .archive.txt was saved not in program folder (I am using the portable version of Vividl) but on Desktop (my default download folder). Moving file .archive.txt has no effect, it is always saved on Desktop. I think that .archive.txt should be saved in program folder (next to executable- Vividl.exe) for portable version and in AppData for installer version. What do you think?

Currently, the archive is kept on a per-folder basis, so this behaviour was intended. However, I'm open to change this as I'm thinking of replacing the archive feature provided by youtube-dl with something own anyway.

**Comment by smaragdus** [comment]
@alxnull 

> I was able to reproduce this issue now. If I'm right, the failure happens for the "Best Download" option and all formats that are shown additionally when "Show all available formats" is enabled in the settings. Does this match with your observations?

Yes, this is exactly what I found out to be causing the failed downloads. I think this bug must have been introduced in version [0.2.0.0](https://sourceforge.net/projects/vividl/files/v.0.2.0/) as I don't encounter it in version [0.1.1.0](https://sourceforge.net/projects/vividl/files/v.0.1.1/).

> I've already found the cause for this bug and I'm in the process of fixing it. Thanks again for your patience and your efforts in finding and reporting this issue, really appreciate that. Would you mind testing the application to confirm that the issue is resolved also on your side before I release a new update? (I would provide you a pre-release binary for testing.)

I really like [Vividl](https://sourceforge.net/projects/vividl/) and I would be glad to be able to contribute a bit to its development with doing some tests. If there are any pre-releases feel free to upload them and I will do some testing (if everything is normal- within 48 hours).

> Currently, the archive is kept on a per-folder basis, so this behaviour was intended.

I see,

> However, I'm open to change this as I'm thinking of replacing the archive feature provided by youtube-dl with something own anyway.

I think that it might be better if the program uses and keeps its own list of downloaded videos in its own format which would mean that the list of previously downloaded videos would be persistent and would not be lost after the program is closed and restarted (if the feature to keep download list is enabled).

Regards

**Comment by alxnull** [comment]
> I think this bug must have been introduced in version 0.2.0.0 as I don't encounter it in version 0.1.1.0.

You're right, this bug is new to version 0.2.0.

> I really like Vividl and I would be glad to be able to contribute a bit to its development with doing some tests. If there are any pre-releases feel free to upload them and I will do some testing.

I've uploaded a binary for testing (portable version only) at https://vividl.sourceforge.io/vividl-pre-releases/Vividl-v.0.2.1-Portable.zip. This version should have fixed the download issues you reported and added an additionaly checkbox in the settings that disables automatic update checking. (I haven't changed anything for the download history yet). Would be great if you could test this binary to check whether all issues are removed. Thanks!

**Comment by smaragdus** [comment]
@alxnull 

I downloaded and tested the version you provided. I downloaded 9 videos using different settings and all the videos were downloaded successfully. However I noticed something else- when I manually selected best MP4 resolution:

- mp4 - 137 - 1920x1080 (1080p)

 screen:

![Vividl 0 2 1 - 2020-03-26 - 001](https://user-images.githubusercontent.com/9025757/77675452-a4910880-6f95-11ea-8a8d-a0bfcf886c0c.png)

The video was downloaded without audio. Can you confirm this?

In short, it seems that version 0.2.1 fixed the problem introduced in version 0.2.0. Also, thank you for adding a check-box for:

Automatically check for updates at startup

screen:

![Vividl 0 2 1 - 2020-03-26 - 002](https://user-images.githubusercontent.com/9025757/77676036-6c3dfa00-6f96-11ea-8877-ff6a2c0f90c8.png)

It is fine update check to be on by default but it is nice to be able to disable it (in circumstances like this one when there is a problem with the latest version).

Thank you for the quick fix!

If you don't encounter other problems you may close this issue.

I will do more tests and if I notice a problem I will report it.

**Comment by alxnull** [comment]
Thank you very much for the testing. I just published the new version ([v.0.2.1](https://sourceforge.net/projects/vividl/files/v.0.2.1/)) containing the fixes.

> The video was downloaded without audio. Can you confirm this?

Yes, I can confirm this. The additional download formats are downloaded as provided by the websites. YouTube seems to provide this specific format as a video only format.

**Comment by smaragdus** [comment]
@alxnull 

Thanks for releasing version [0.2.1](https://sourceforge.net/projects/vividl/files/v.0.2.1/).
