### ISSUE TITLE
download speed

### ISSUE THREAD

**Issue by eetsceeck1** [Bluegrams/Vividl#40]
HI,
first i want to thank you for this program, 
it works well so far, i did download it last night for the first time after i was looking for an alternative to mediahuman, 
but to be honest after i did tried so many similar programs, none of them did even came close to mediahuman video downloader, 

but, at least i found this particular program, vividl, as the most best among the others, 

but there is a small problem with it, just a small one,
i really don't understand why vividl downloading in maximum speed of 80kbps ?

even the other open source programs did download in at least 250 kbps, 

vividl downloading in exactly between 79 to 80.01 kbps so its looks like its definitely in purpose?
mm.. i am not sure what's going on, 
there is any conf file to bypass it? cause at the interface itself it doesn't looks like there are any options to increase speed, 

can you fix it somehow? or can at least explain why is it like that?

my internet speed by the way is a 100mbps which means i am able to download in a speed of 3 real mega bytes per second, 
cause i am connected with wifi and i am loosing speed, but my current maximum speed is 3mb which 80kb is just 3% of my internet download speed

thank you

**Comment by smaragdus** [comment]
@eetsceeck1 

I am not the developer but I suppose that [YouTube](https://www.youtube.com/) may be throttling downloads (see this [youtube-dl issue](https://github.com/ytdl-org/youtube-dl/issues/29326) and this [reddit thread](https://www.reddit.com/r/youtubedl/comments/piielc/download_speed_is_throttling/)).

**Comment by smaragdus** [comment]
@levicki 

I suppose that [youtube-dl](https://github.com/ytdl-org/youtube-dl) is most likely [abandoned](https://github.com/ytdl-org/youtube-dl/issues/29965).

**Comment by alxnull** [comment]
Since v.0.6.0, Vividl now comes with yt-dlp instead of youtube-dl as the download engine by default. From my experiments, this significantly increases download speeds.

**Comment by eetsceeck1** [comment]
Thank you all 
alxnull Thanks for update

> Since v.0.6.0, Vividl now comes with yt-dlp instead of youtube-dl as the download engine by default. From my experiments, this significantly increases download speeds.
