### ISSUE TITLE
Exe version

### ISSUE THREAD

**Issue by trimechee** [Bluegrams/Vividl#48]
Hello, thank you very much for this magnificent and awesome software ! please it will be great if Vividl can make a .exe version on github for an even easier and more usual installation! thank you so much :)

**Comment by alxnull** [comment]
Hey @trimechee, currently, there are two ways in which binaries for Vividl are made available:

1. Direct download of the files [via SourceForge](https://sourceforge.net/projects/vividl/files/)
2. Installation with package manager [via Chocolatey](https://community.chocolatey.org/packages/vividl)

These two release channels should provide flexibility for different setup scenarios.

**Comment by trimechee** [comment]
Great, thank you very much :)
