### ISSUE TITLE
Disable Update Check

### ISSUE THREAD

**Issue by smaragdus** [Bluegrams/Vividl#5]
Please consider adding an option to disable update check on program start. As I commented [here](https://github.com/Bluegrams/Vividl/issues/4#issuecomment-602379876) version [0.2.0.0](https://sourceforge.net/projects/vividl/files/v.0.2.0/) did not work for me and the update prompt, screen:

![Vividl 0 1 1 0 - 2020-03-23 - 003](https://user-images.githubusercontent.com/9025757/77281798-c148ea00-6cd0-11ea-9283-4594f379f760.png)

is annoying for me as it appears any time I start the program.

**Comment by smaragdus** [comment]
@alxnull 

Thanks for adding a check box for disabling update check:

![Vividl 0 2 1 0 - 2020-03-27 - 001](https://user-images.githubusercontent.com/9025757/77781647-9fe45700-705e-11ea-9ed3-6a409d463712.png)

However when I manually execute `Check For Updates` command I got the following error:

![Vividl 0 2 1 0 - 2020-03-27 - error - 002](https://user-images.githubusercontent.com/9025757/77781775-cefac880-705e-11ea-9678-60a6dee246ed.png)

- Software Update - Error
  - Update check failed.
  - Please check for updates manually.

Did you get this error when you press `Check For Updates` button?

**Comment by alxnull** [comment]
> Did you get this error when you press Check For Updates button?

This happened because update checking was disabled until the new version was released. Should be working now.

**Comment by smaragdus** [comment]
@alxnull 

Thanks for the explanation, it really works now, screen:

![Vividl 0 2 1 0 - 2020-03-28 - 002](https://user-images.githubusercontent.com/9025757/77807764-7ee92980-7091-11ea-8b96-a40cd81bde7d.png)

Regards
