### ISSUE TITLE
Check for Updates doesn't check for yt-dlp update too

### ISSUE THREAD

**Issue by as-muncher** [Bluegrams/Vividl#50]
vividl 0.6.0.0

When I select Options -> Check for updates, it only checks for the program update, not yt-dlp update too.  I have to go manually to Options -> Settings -> Application and manually select "check for updates" for the program and for yt-dlp.  What should happen is that when I do a check for updates, all updates should be checked for, not just for the program.

Also, the yt-dlp version should probably show up in About too.

**Comment by alxnull** [comment]
This makes sense, I'll modify the "Check for updates" menu item to also check for yt-dlp updates.
