### ISSUE TITLE
download button and other buttons diseappear

### ISSUE THREAD

**Issue by as-muncher** [Bluegrams/Vividl#51]
vividl 0.6.0.0
For some reason, the yt-dlp version doesn't show in the About window.

So, one video was converting to mkv, and then the other videos: their download buttons and other buttons just disappeared.  I've had to copy the video links to a .txt file and have to restart vividl so I can re-add the links.

**Comment by as-muncher** [comment]
This seems to happen while the video preview is being fetched for the last video, and then the download and other buttons appear again.  This should not happen this way.  If I want to download the first video, I don't want to have to wait until the preview for the final video shows up in order to get started on downloading, or to get started on downloading while another video is converting.

**Comment by alxnull** [comment]
Hey, this definitely does not sound like intended behavior. Unfortunately, I'm currently unable to reproduce the issue you describe on my side. Could you give some more specific instructions on how I can reproduce it (e.g. URL import method, maybe a list of example URLs etc.). Thanks!

**Comment by as-muncher** [comment]
You'll have to wait until it happens again.  Maybe it's a problem with Windows and not so much with your software?  not sure.  It hasn't happened since.

**Comment by as-muncher** [comment]
It's been a while since this happened.  Perhaps I should close it for now and then re-open it later if it reoccurs.
