### ISSUE TITLE
app crashes upon inserting video links

### ISSUE THREAD

**Issue by vitalitasia** [Bluegrams/Vividl#53]
app crashes randomly upon inserting video links, tried "ctrl+n" and "ctrl+v". both crash before thumbnail and video info can be displayed

example:  https://www.youtube.com/shorts/9SyC5Ouxtp4

video is a short, but not only shorts are affected, in yt-dlp cmd can be downloaded as usual

**Comment by alxnull** [comment]
Hey. unfortunately, I wasn't able to reproduce the issue using the link you shared. Are you using the latest versions of Vividl (0.6.0) and yt-dlp?

**Comment by vitalitasia** [comment]
> Hey. unfortunately, I wasn't able to reproduce the issue using the link you shared. Are you using the latest versions of Vividl (0.6.0) and yt-dlp?

Hi, problem was fixed after repairing VC++ 2010 Redistributable Package, its weird though since not all videos were affected, but having no issues lately. thanks for the reply

**Comment by alxnull** [comment]
Great to hear! Closing this issue then. Thanks for using Vividl :)
