### ISSUE TITLE
Progress bar no more showing

### ISSUE THREAD

**Issue by JonnyThree** [Bluegrams/Vividl#57]
With new versions of yt-dlp, the downloading progress bar with all the other stats is disappeared, is this a bug of the Vividl GUI? Using old versions of yt-dlp all is ok

**Comment by alxnull** [comment]
Hi, unfortunately, I wasn't able to reproduce this issue on my side. Could you add some more details, e.g. Vividl version, yt-dlp version, OS version, example video link, to help me reproduce your issue so I can fix it? Thanks!

**Comment by JonnyThree** [comment]
Windows 7 Pro x64
Vividl v.0.6.0
yt-dlp 2022.10.04

Downloading this link:
https://www.discoveryplus.com/it/video/motors-motortrend-it/stagione-2-episodio-4

**Comment by alxnull** [comment]
Thanks, I was able to identify the source of your issue now. This will be fixed with the next release.

**Comment by JonnyThree** [comment]
> Thanks, I was able to identify the source of your issue now. This will be fixed with the next release.

Very good! Vividl is the best GUI for yt-dlp, thanks for your work
