### ISSUE TITLE
Auto Import from clipboard stopped working

### ISSUE THREAD

**Issue by wankin99** [Bluegrams/Vividl#58]
The auto import URLS from clipboard stopped working.  Icon lights up like it's enabled but it's not adding the URLs automatically.  The manual paste function on the GUI does add the URL link.

Great program BTW!

**Comment by alxnull** [comment]
Hey, unfortunately, I'm currently not able to reproduce this issue on my side. Maybe it would help me if you could add some additional info: Have you specified a URL filter pattern for the auto import in the settings? Does it work for some URLs or for none? Did you change any settings or upgrade yt-dlp before it stopped working? Thanks!

**Comment by wankin99** [comment]
I feel like such an amateur!  It was the URL filter pattern.  Sorry for wasting your time and thanks for getting back to me!
