### ISSUE TITLE
Feature Request: download audio only without conversion

### ISSUE THREAD

**Issue by ghost** [Bluegrams/Vividl#59]
Would it be possible to add an option to download (specifically youtube) videos audio only without conversion? I know we can save full videos as mkv which doesn’t convert anything. But in terms of audio only, the best we have is wav.

**Comment by alxnull** [comment]
Hey @Alann-Mints, the current version of Vividl already allows you to directly download audio formats provided by a website without conversion. You can select those from the format selection dropdown. E.g. for a YouTube video:

![grafik](https://user-images.githubusercontent.com/26907770/209843187-58a01e44-0ad9-4219-b5a9-3ce83c050ad0.png)

If these formats are not shown by default for you, you might have to enable them beforehand (Settings -> General -> Check "Show all available formats").

Let me know if this is not what you were looking for.

**Comment by Alann-Mints** [comment]
I didn’t think to do that. It’s partially solved the “problem”. However, it would be cool to be able to do it for everything in the queue without doing it one-by-one. An option such as “Audio only (best quality)” would be very nice to have.

I understand this might be a bit difficult to implement, but I thought if the audio is mp3, it can be saved as .mp3. If the audio is opus, it can be saved at .opus, etc.

Either way, thank you for letting me know how to do it on a per video basis.

**Comment by alxnull** [comment]
> However, it would be cool to be able to do it for everything in the queue without doing it one-by-one. An option such as “Audio only (best quality)” would be very nice to have.

This sounds sensible. Will keep this issue open as a feature request.

**Comment by alxnull** [comment]
A new "Best Audio-only Download" download option will be added in the upcoming release (v.0.8.0).
