### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by rocky53204** [Bluegrams/Vividl#6]
virus detected upon download!

**Comment by alxnull** [comment]
Could you add some details to this? Does this happen when downloading the software from the download page? Or when downloading a video? What exactly is flagged as malicious?

You should download Vividl from the official download page at https://sourceforge.net/projects/vividl/ and not from any third-party sites. All projects an SourceForge.net are automatically scanned for malware: https://sourceforge.net/blog/is-sourceforge-net-safe/.

The binaries on SourceForge are directly built from the source here on GitHub. If you don't trust these binaries, you may want to build the software yourself from source using Visual Studio.

As the binaries of Vividl are unsigned and the software internally calls two external executables (youtube-dl.exe and ffmpeg.exe) there still is a possibility that your antivirus software falsely flags Vividl as malware.

**Comment by rocky53204** [comment]
Windows 10 and windows security... upon download I get this message:
"VividdlSetup.msi contained a virus and was deleted."
came from cfhcable.dl.sourceforge.net

**Comment by alxnull** [comment]
> I have used this program in the past without issues.

Since you used this software previously, are you still able to download older versions without issues? Or does downloading the [portable Zip version](https://sourceforge.net/projects/vividl/files/v.0.2.1/Vividl-v.0.2.1-Portable.zip/download) instead of the msi installer work?

You could also check if downloading different software or using a different browser for downloading works without issues.

**Comment by rocky53204** [comment]
The portable zip version downloaded and ran without issues! Thanks!

**Comment by alxnull** [comment]
Great. Meanwhile, I submitted the installer file as a false positive to [Microsoft's malware analysis system](https://www.microsoft.com/en-us/wdsi/filesubmission), so Windows Defender shouldn't detect the file as malicious anymore.

Here is a quick check of the file on VirusTotal (including Microsoft anti-virus), verifying the file is clean: https://www.virustotal.com/gui/file/d47fa6f72cb3be9c354610f78f21dc8ee0f7161b67e5f7b4b10fb4dfbc8fd008/detection

P.S.: If this helped you, please consider updating your one-star rating on SourceForge saying the software is malicious. Thanks!

**Comment by alxnull** [comment]
Closing with release of v.0.2.2 ([check](https://www.virustotal.com/gui/file/3f1055189020fdb033b20ce9c8d903ab70e95a5a810212fd9bffb67613ea770b/detection)).
