### ISSUE TITLE
Suggestions regarding installer

### ISSUE THREAD

**Issue by Alann-Mints** [Bluegrams/Vividl#60]
I think it would be a good idea to include ".NET Framework v.4.6.2"
 & "Microsoft Visual C++ 2010 Redistributable Package (x86)" in the installer. It simplifies things for the user, and prevents cases when links go down (like they are now in the readme)

**Comment by bao000** [comment]
> Tôi nghĩ nên đưa ".NET Framework v.4.6.2" & "Microsoft Visual C++ 2010 Redistributable Package (x86)" vào trình cài đặt. Nó đơn giản hóa mọi thứ cho người dùng và ngăn chặn các trường hợp khi liên kết bị hỏng (giống như chúng hiện đang ở trong readme)

https://github.com/Bluegrams/Vividl/issues/60#issue-1411626851

**Comment by alxnull** [comment]
Thanks for bringing up the broken links in the readme, I've updated those with new download links.

Currently, the installer intentionally is not bundled with these dependencies, especially .NET Framework should be pre-installed on most recent Windows systems. However, the alternative installation path via Chocolatey does automatically attempt to install both .NET and Visual C++ 2010 via Chocolatey packages if required.
