### ISSUE TITLE
Shorts Download not working

### ISSUE THREAD

**Issue by megabugman** [Bluegrams/Vividl#61]
example: https://www.youtube.com/shorts/GesHBggE2Mc

**Comment by alxnull** [comment]
Hey @megabugman, does this issue still persist for you? I could successfully download the video you linked with Vividl v.0.6.0 and yt-dlp 2022.11.11.

**Comment by techdragon** [comment]
Shorts download is definitely working for me (after fixing things in #74) 

Downloading a short was what prompted me to update yt-dlp and wind up with the json error and ended up writing the pull request. Downloading a short from youtube was my first test after I built my new version, and it worked fine 👍

**Comment by alxnull** [comment]
The latest release, [v.0.7.0](https://github.com/Bluegrams/Vividl/releases/tag/v.0.7.0), should resolve this issue. If this is not the case, please re-open this issue and provide further details.
