### ISSUE TITLE
Message: Illegal Characters in path

### ISSUE THREAD

**Issue by megabugman** [Bluegrams/Vividl#63]
https://youtu.be/s2jU2T269AE?list=PLhG2EKj_7AzC44lvoa10PNFlh6zT5BhFw

JDownloader prompts a message:
The youtube link contains a vid and a playlist. what do you want to download? Only vid / complete list.

**Comment by alxnull** [comment]
I could successfully download the video you linked with the latest Vividl v.0.6.0 and yt-dlp 2022.11.11. Please make sure you use the latest versions for both.
