### ISSUE TITLE
Post-Processor arguments given without specifying name

### ISSUE THREAD

**Issue by Xandorion** [Bluegrams/Vividl#65]
This is just a example video, but i get this error warning for all videos which i want to download as MP3.

"KIRA - Bad Apple!! (German Version) ft. Akarui Kouki [GERMAN VCV TEST COVER]":
WARNING: Post-Processor arguments given without specifying name. The arguments will be given to all post-processors

Link from the YouTube video: https://www.youtube.com/watch?v=1pUXLuIBCKQ

I use the portable version, is the a solution for the Problem?

**Comment by alxnull** [comment]
Thanks for bringing up this issue. I just added a fix for this on the master branch which will be released with the next update.
