### ISSUE TITLE
Is there a way to limit all downloads to 1080p?

### ISSUE THREAD

**Issue by lucidtyper** [Bluegrams/Vividl#72]

**Comment by alxnull** [comment]
The upcoming release will add a new option to specify a preferred video resolution to download. This will result in Vividl automatically preferring formats with the specified resolution for direct downloads and video conversion downloads. The new options is available via:
- the settings window at "General -> Download List -> Preferred Video Resolution"
- the window for adding new videos when expanding the "Options" section
