### ISSUE TITLE
New release build?

### ISSUE THREAD

**Issue by techdragon** [Bluegrams/Vividl#76]
With the crash issue if users let the program upgrade to the latest version of `yt-dlp` it might be worth doing a new release build @alxnull  

Getting the #74 fixes into a release might prevent additional "its crashing" posts. 

I wrote my PR off what I saw in #68, but there's also #61 and now #75 that could also be the same underlying issue that has already been fixed.

**Comment by alxnull** [comment]
Hey, thanks for the reminder and sorry for the delay on my side. I just pushed a new release, [v.0.7.0](https://github.com/Bluegrams/Vividl/releases/tag/v.0.7.0) today. Hopefully, this resolves most of the open bug reports.
