### ISSUE TITLE
Add: Show log.  or Open log file

### ISSUE THREAD

**Issue by as-muncher** [Bluegrams/Vividl#79]
vividl 0.6.0.0

It would be nice to have a feature where I could view the log.  Show log.  Or "Open log".  something to that effect.
I know I have to search for vividl.log, but when reporting errors, it would be nice to have "Show Log" or something like that.

**Comment by alxnull** [comment]
The latest release, [v.0.7.0](https://github.com/Bluegrams/Vividl/releases/tag/v.0.7.0), adds a main menu item to directly open the error log if available. You can find it under Options -> Open Error Log.
