### ISSUE TITLE
Could not retrieve video

### ISSUE THREAD

**Issue by JensDeLeersnyderPXL** [Bluegrams/Vividl#80]
When trying to download any new video, I always get the error of could not retrieve video.

url I Used: https://youtu.be/AzaTyxMduH4
Vividl version: 0.6.0.0
Youtube dl version: 2021.12.27

**Comment by alxnull** [comment]
The latest release, [v.0.7.0](https://github.com/Bluegrams/Vividl/releases/tag/v.0.7.0), should resolve this issue. If this is not the case, please re-open this issue and provide further details.
