### ISSUE TITLE
vividl couldn't detect software update

### ISSUE THREAD

**Issue by as-muncher** [Bluegrams/Vividl#83]
hi, vividl 0.6.0.0 (is it necessary to have all these numbers like this?) couldn't detect that there is 0.7.00 available.
I'm not sure if this issue will carry into 0.7.0.0 not being able to find later versions, too.

using win11 x64

**Comment by alxnull** [comment]
Hey, I intentionally push the update notification a few days after the actual release to ensure there are no serious issues in the updated version when the notification is pushed to everyone. Vividl should now be able to find the new version via the update checker.

**Comment by as-muncher** [comment]
It's been 3 weeks since 0.7.1 was released, and my version 0.7 is still not detecting a vividl update.
