### ISSUE TITLE
how to make vividl on more websites?

### ISSUE THREAD

**Issue by as-muncher** [Bluegrams/Vividl#85]
using vividl 0.7.0.0

One thing I like about it is that it can keep the downloaded video as mkv instead of always having to convert it to mp4 as so many other video downloaders.  A lot of downloaders won't even support some sites.  How can we get vividl to work on more websites?  Post the links here?  of course, some of these websites are adult web sites.  but not all.

**Comment by alxnull** [comment]
Vividl uses [yt-dlp](https://github.com/yt-dlp/yt-dlp) as the download engine . Therefore, it supports all sites listed here: https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md. If there's any site missing from that list, please open a feature request over in the yt-dlp repository as support for new sites is not implemented here.
