### ISSUE TITLE
[Bug] Setting doesn't save when not in the setting's tab

### ISSUE THREAD

**Issue by orkeilius** [Bluegrams/Vividl#90]
Setting doesn't save when not in the setting's tab
(work fine if you save setting while on the tab)

https://user-images.githubusercontent.com/63045634/235104640-695a60cf-8a29-4896-a5dd-adb3cf508148.mp4

### information
Vividl version : 0.7.0.0

**Comment by alxnull** [comment]
Thanks for reporting! I've just fixed this issue and will release the fix with the next version.
