### ISSUE TITLE
Cookie options like ytdlp

### ISSUE THREAD

**Issue by Cy9oz** [Bluegrams/Vividl#96]
Is there a cookie option like ytdlp?
I want to record the stream of a paid subscriber, but I can't do it with my login and password!
Is there a solution?

Case:yt-dlp --cookies cookies.txt https://www.youtube.com/watch?v=xxxxxx

**Comment by alxnull** [comment]
Hey, while there's no option to set this directly in the settings UI, you can always directly add the yt-dlp option directly as a custom argument. To do this, go to Settings -> Advanced -> Custom Downloader Arguments and add the `--cookies` flag as custom argument. Hope this helps!

**Comment by Cy9oz** [comment]
I was able to solve it by adding an argument to the Cookie! 
Thank you very much.

**Comment by Cy9oz** [comment]
> Hey, while there's no option to set this directly in the settings UI, you can always directly add the yt-dlp option directly as a custom argument. To do this, go to Settings -> Advanced -> Custom Downloader Arguments and add the `--cookies` flag as custom argument. Hope this helps!

I was able to solve it by adding an argument to the Cookie! 
Thank you very much.
