### ISSUE TITLE
only showing up to 720p by default

### ISSUE THREAD

**Issue by codeduph** [Bluegrams/Vividl#97]
the default conversion is only up to 720p... 

how can you make it to atleast 1080p?

![2023-06-17_000202](https://github.com/Bluegrams/Vividl/assets/16449014/c682f5ce-e4ca-43e9-8d78-37a7565cc838)
![2023-06-17_000225](https://github.com/Bluegrams/Vividl/assets/16449014/f58aa0fb-ee06-4490-bd88-420b6a042d57)

**Comment by alxnull** [comment]
Hey, if no resolution beyond 720p is shown in the list on the dialog you shared, then no better resolution is available for direct download. You can check the second tab "Video/ Audio only" to see if a video-only version with a higher resolution is available (you could merge that video-only version with one of the provided audio tracks then).
