### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Yagaami** [Bluegrams/Vividl#98]
this error happens whenever i try to download a video. Error shows couldn't fatch video info... i have everything updated and have the latest seal apk update

**Comment by alxnull** [comment]
Hey, could you share the link to a video where this issue occurs so I can help you debug this? Thanks!

**Comment by reddvid** [comment]
Happens to me as of the moment with the latest portable version of the app and even building from source (re-imported ffmpeg and yt-dlp to project files).

Tried two links (old video and a recent one) with a similar program called yt-dl-wpf, which both works, but NOT on Vividl. 

yt-dl-wpf reported an error when I have selected a specific output download/format (1080p AVC + AAC MP4): <pre> ERROR: [youtube] aAPCaoiItz4: Requested format is not available.</pre>

**Comment by reddvid** [comment]
Update: Found the issue, I might have been using an older version of yt-dlp (or ffmpeg?).

Ran the DownloadBinaries powershell script to download the latest ones and the app now works as intended.
